Repository wanted-pre-onboarding-fe-8/8ripbtoz, pull requests merged in 2022-08, with the labels that each got.

#3 예약일 선택 UI 구현
  src/components/datepicker/index.tsx
  src/utils/constants/time.ts
Labels: enhancement

#2 JSON Server 구현
  package-lock.json
  package.json
  public/database/hotels.json
  src/http/index.ts
Labels: enhancement

#5 예약내역 페이지 UI 구현
  src/pages/reservation/ReservationCard.tsx
  src/pages/reservation/index.tsx
Labels: enhancement

#7 검색 결과 카드 레이아웃 깨지는 현상 수정
  src/pages/main/card/Card.tsx
  src/pages/main/card/GridCard.tsx
  src/pages/main/card/index.tsx
Labels: enhancement

#9 스켈레톤 ui 구현
  src/pages/main/card/Skeleton.tsx
  src/pages/main/card/index.tsx
Labels: enhancement

#8 통신 작업 - React query
  package-lock.json
  public/database/hotels.json
  src/index.tsx
  src/pages/main/card/Card.tsx
  src/pages/main/index.tsx
  src/queries/hotel.ts
  src/types/index.ts
Labels: enhancement

#14 예약일 선택 바디 UI 오류 수정
  src/components/datepicker/Body.tsx
  src/components/datepicker/index.tsx
Labels: bug

#15 헤더바 구현
  src/components/Header.tsx
Labels: enhancement

#17 예약버튼 누르면 로컬스토리지 및 DB에 저장
  src/hooks/useScheduleValue.ts
  src/pages/main/card/Card.tsx
  src/pages/main/index.tsx
  src/types/index.ts
  src/utils/constants/time.ts
  src/utils/date.ts
  src/utils/storage.ts
Labels: enhancement

#23 PC 모드 예약일 지정 UI 메인 페이지에 연동하기
  public/index.html
  src/components/datepicker/Calendar.tsx
  src/components/datepicker/Navigation.tsx
  src/components/datepicker/Weekdays.tsx
  src/components/datepicker/index.tsx
  src/components/datepicker/types.ts
  src/pages/main/search/desktop/Schedule.tsx
Labels: enhancement

#24 로컬스토리지에 있는 호텔 데이터들 불러오기 구현
  src/pages/reservation/ReservationCard.tsx
  src/pages/reservation/index.tsx
  src/types/index.ts
  src/utils/date.ts
  src/utils/storage.ts
Labels: enhancement

#25 예약일 지정 UI 버그 수정
  src/components/datepicker/Calendar.tsx
  src/components/datepicker/index.tsx
  src/types/index.ts
Labels: bug

#26 예약일 지정 UI 노출 위치 수정
  src/components/datepicker/index.tsx
  src/pages/main/search/Popup.tsx
Labels: bug

#27 통신 - InfiniteScroll
  package-lock.json
  package.json
  src/http/index.ts
  src/pages/main/card/Card.tsx
  src/pages/main/index.tsx
  src/queries/hotel.ts
  src/types/index.ts
Labels: enhancement

#28 호텔정보 카드 스타일 수정
  src/pages/main/card/Card.tsx
  src/pages/main/card/GridCard.tsx
  src/pages/main/card/Skeleton.tsx
  src/pages/main/index.tsx
  src/utils/storage.ts
Labels: style

#31 호텔 지낼 일 버그 수정
  src/pages/reservation/ReservationCard.tsx
Labels: bug

#32 예약 페이지 UI 개선
  src/pages/reservation/ReservationCard.tsx
  src/pages/reservation/index.tsx
Labels: style

#35 infiniteScroll 무한 호출 에러 수정
  src/pages/main/index.tsx
  src/queries/hotel.ts
Labels: bug

#34 예약일 지정 UI 리팩토링
  src/components/datepicker/Calendar.tsx
  src/components/datepicker/Day.tsx
  src/components/datepicker/Navigation.tsx
  src/components/datepicker/Weekdays.tsx
  src/components/datepicker/index.tsx
  src/pages/main/search/mobile/Schedule.tsx
Labels: enhancement

#36 리드미 작성
  README.md
Labels: documentation

#39 자잘한 버그랑 수정사항
  README.md
  src/pages/main/card/Card.tsx
  src/pages/main/card/CardContainer.tsx
  src/pages/main/card/Skeleton.tsx
  src/pages/main/index.tsx
Labels: bug

#43 검색 결과 없음 표시
  src/components/guestselect/GuestSelect.tsx
  src/components/guestselect/GuestSelectButton.tsx
  src/pages/main/card/Card.tsx
  src/pages/main/card/CardLayouts.tsx
  src/pages/main/card/Skeleton.tsx
  src/pages/main/index.tsx
  src/queries/hotel.ts
Labels: bug
